apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    url: db:5432
    user: volmax
    secureJsonData: {password: volmax}
    jsonData:
      database: edge
      sslmode: disable
      timescaledb: true
    isDefault: true
